version: "3.7"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/app:cached
    ports:
      - 80:80
    depends_on:
      - fpm
  fpm:
    build: ./docker/fpm
    env_file:
      - ./.env
      - ./.env.local
    volumes:
      - ./:/app:cached
    working_dir: /app
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - ./.env
      - ./.env.local
    volumes:
      - ./docker/db/lib:/var/lib/mysql:rw
  node:
    image: node:latest
    volumes:
      - ./:/app:cached
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    working_dir: /app